name: food_delivery
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  introduction_screen: ^3.1.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/part1/box_front.png
    - assets/images/part1/cheese.png
    - assets/images/part1/cheese2.jpg
    - assets/images/part1/chili.png
    - assets/images/part1/dish.png
    - assets/images/part1/garlic.png
    - assets/images/part1/olive.png
    - assets/images/part1/onion.png
    - assets/images/part1/pea.png
    - assets/images/part1/pickle.png
    - assets/images/part1/pizza-0.png
    - assets/images/part1/pizza-1.png
    - assets/images/part1/pizza-2.png
    - assets/images/part1/pizza-4.png
    - assets/images/part1/pizza-3.png
    - assets/images/part1/pizza-5.png
    - assets/images/part1/pizza-6.png
    - assets/images/part1/pizza-8.png
    - assets/images/part1/pizza-9.png
    - assets/images/part1/pizza-10.png
    - assets/images/part1/potato.png #part1
    - assets/images/part2/box_front.png
    - assets/images/part2/cheese.png
    - assets/images/part2/cheese2.jpg
    - assets/images/part2/chili.png
    - assets/images/part2/chili_unit.png
    - assets/images/part2/dish.png
    - assets/images/part2/mushroom.png
    - assets/images/part2/mushroom_unit.png
    - assets/images/part2/olive.png
    - assets/images/part2/olive_unit.png
    - assets/images/part2/onion.png
    - assets/images/part2/pea.png
    - assets/images/part2/pea_unit.png
    - assets/images/part2/pickle.png
    - assets/images/part2/pickle_unit.png
    - assets/images/part2/pizza-0.png
    - assets/images/part2/pizza-1.png
    - assets/images/part2/pizza-2.png
    - assets/images/part2/pizza-3.png
    - assets/images/part2/pizza-4.png
    - assets/images/part2/pizza-5.png
    - assets/images/part2/pizza-6.png
    - assets/images/part2/pizza-8.png
    - assets/images/part2/pizza-9.png
    - assets/images/part2/pizza-10.png
    - assets/images/part2/potato.png
    - assets/images/part2/potato_unit.png #part2
    - assets/images/part3/box_diegoveloper.png
    - assets/images/part3/box_front.png
    - assets/images/part3/box_inside.png
    - assets/images/part3/chili.png
    - assets/images/part3/chili_unit.png
    - assets/images/part3/dish.png
    - assets/images/part3/mushroom.png
    - assets/images/part3/mushroom_unit.png
    - assets/images/part3/olive.png
    - assets/images/part3/olive_unit.png
    - assets/images/part3/onion.png
    - assets/images/part3/pea.png
    - assets/images/part3/pea_unit.png
    - assets/images/part3/pickle.png
    - assets/images/part3/pickle_unit.png
    - assets/images/part3/pizza-0.png
    - assets/images/part3/pizza-1.png
    - assets/images/part3/pizza-2.png
    - assets/images/part3/pizza-3.png
    - assets/images/part3/pizza-4.png
    - assets/images/part3/pizza-5.png
    - assets/images/part3/pizza-6.png
    - assets/images/part3/pizza-8.png
    - assets/images/part3/pizza-9.png
    - assets/images/part3/pizza-10.png
    - assets/images/part3/potato.png
    - assets/images/part3/potato_unit.png #part3
    - assets/images/profile_pic.png
    - assets/images/logo/profil.png
    - assets/images/background/login_background.png
    - assets/images/logo/Chef Logo.png
    - assets/images/loginfood.png
    - assets/images/happy/Momos.png
    - assets/images/happy/broccoli.png
    - assets/images/happy/cabbage.png
    - assets/images/happy/carrot.png
    - assets/images/happy/onion.png
    - assets/images/happy/corn.png
    - assets/images/happy/redpepper.png
    - assets/images/background/bbq.png
    - assets/images/foodlist/burger.png
    - assets/images/foodlist/maggie.png
    - assets/images/foodlist/panipuri.png
    - assets/images/foodlist/pizza.png
    - assets/images/foodlist/samosa.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
